(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }
  const schema = factory();
  root.DataChartsSchema = schema;
  root.DataChartsWebSchema = schema;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const SKILL_STATIC_ROOT = "../../../skills/data-charts-visualization/static";

  const PERCENT_OPTIONS = [
    "0%",
    "3%",
    "6%",
    "9%",
    "12%",
    "15%",
    "18%",
    "21%",
    "24%",
    "27%",
    "30%",
    "33%",
    "36%",
    "39%",
    "42%",
  ];

  const FONT_SIZE_OPTIONS = ["10", "12", "14", "16", "18", "20", "22", "24"];
  const SPLIT_WIDTH_OPTIONS = ["0.6", "1", "1.6"];
  const LINE_STYLE_OPTIONS = [
    ["solid", "Solid"],
    ["dashed", "Dashed"],
    ["dotted", "Dotted"],
  ];
  const SYMBOL_OPTIONS = [
    ["circle", "Circle"],
    ["rect", "Rect"],
    ["triangle", "Triangle"],
    ["diamond", "Diamond"],
  ];

  const COMMON_GROUPS = [
    {
      id: "title",
      label: "标题",
      fields: [
        { id: "titleShow", label: "显示主标题", type: "checkbox" },
        {
          id: "titleAlign",
          label: "标题对齐",
          type: "select",
          options: [
            ["left", "Left"],
            ["center", "Center"],
            ["right", "Right"],
          ],
        },
        { id: "titleFontSize", label: "标题字号", type: "select", options: FONT_SIZE_OPTIONS.map((value) => [value, value]) },
        { id: "titleColor", label: "标题颜色", type: "color" },
        { id: "titleBold", label: "标题加粗", type: "checkbox" },
        { id: "subtitleShow", label: "显示副标题", type: "checkbox" },
        { id: "subtitleFontSize", label: "副标题字号", type: "select", options: FONT_SIZE_OPTIONS.map((value) => [value, value]) },
        { id: "subtitleColor", label: "副标题颜色", type: "color" },
      ],
    },
    {
      id: "legend",
      label: "图例",
      fields: [
        { id: "legendShow", label: "显示图例", type: "checkbox" },
        {
          id: "legendPosition",
          label: "图例位置",
          type: "select",
          options: [
            ["top-left", "Top Left"],
            ["top-center", "Top Center"],
            ["top-right", "Top Right"],
            ["middle-left", "Middle Left"],
            ["middle-right", "Middle Right"],
            ["bottom-left", "Bottom Left"],
            ["bottom-center", "Bottom Center"],
            ["bottom-right", "Bottom Right"],
          ],
        },
        {
          id: "legendOrient",
          label: "图例方向",
          type: "select",
          options: [
            ["horizontal", "Horizontal"],
            ["vertical", "Vertical"],
          ],
        },
        { id: "legendFontSize", label: "图例字号", type: "select", options: FONT_SIZE_OPTIONS.map((value) => [value, value]) },
        { id: "legendColor", label: "图例颜色", type: "color" },
      ],
    },
    {
      id: "canvas",
      label: "画布",
      fields: [
        { id: "backgroundColor", label: "背景色", type: "color" },
        { id: "palette", label: "调色板", type: "textarea" },
        { id: "gridLeft", label: "Plot Left", type: "select", options: PERCENT_OPTIONS.map((value) => [value, value]) },
        { id: "gridRight", label: "Plot Right", type: "select", options: PERCENT_OPTIONS.map((value) => [value, value]) },
        { id: "gridTop", label: "Plot Top", type: "select", options: PERCENT_OPTIONS.map((value) => [value, value]) },
        { id: "gridBottom", label: "Plot Bottom", type: "select", options: PERCENT_OPTIONS.map((value) => [value, value]) },
      ],
    },
    {
      id: "axes",
      label: "坐标轴",
      fields: [
        { id: "xAxisLineShow", label: "显示 X 轴线", type: "checkbox" },
        { id: "xAxisTickShow", label: "显示 X 轴刻度", type: "checkbox" },
        { id: "xRotate", label: "X 标签旋转", type: "number", step: 1 },
        { id: "xAxisLabelFontSize", label: "X 标签字号", type: "select", options: FONT_SIZE_OPTIONS.map((value) => [value, value]) },
        { id: "xAxisLabelColor", label: "X 标签颜色", type: "color" },
        { id: "xAxisLineColor", label: "X 轴线颜色", type: "color" },
        { id: "xFormatter", label: "X Formatter", type: "text" },
        { id: "yAxisLineShow", label: "显示 Y 轴线", type: "checkbox" },
        { id: "yAxisTickShow", label: "显示 Y 轴刻度", type: "checkbox" },
        { id: "yAxisLabelFontSize", label: "Y 标签字号", type: "select", options: FONT_SIZE_OPTIONS.map((value) => [value, value]) },
        { id: "yAxisLabelColor", label: "Y 标签颜色", type: "color" },
        { id: "yAxisLineColor", label: "Y 轴线颜色", type: "color" },
        { id: "yFormatter", label: "Y Formatter", type: "text" },
      ],
    },
    {
      id: "splitLines",
      label: "分割线",
      fields: [
        { id: "splitLineShow", label: "显示横向分割线", type: "checkbox" },
        { id: "splitLineColor", label: "横向分割线颜色", type: "color" },
        {
          id: "splitLineType",
          label: "横向分割线样式",
          type: "select",
          options: LINE_STYLE_OPTIONS,
        },
        { id: "splitLineWidth", label: "横向分割线宽度", type: "select", options: SPLIT_WIDTH_OPTIONS.map((value) => [value, value]) },
        { id: "xSplitLineShow", label: "显示纵向分割线", type: "checkbox" },
        { id: "xSplitLineColor", label: "纵向分割线颜色", type: "color" },
        {
          id: "xSplitLineType",
          label: "纵向分割线样式",
          type: "select",
          options: LINE_STYLE_OPTIONS,
        },
        { id: "xSplitLineWidth", label: "纵向分割线宽度", type: "select", options: SPLIT_WIDTH_OPTIONS.map((value) => [value, value]) },
      ],
    },
  ];

const LOCALIZED_DEFINITION_TEXT = {
  zh: {
    line: {
      label: "折线图",
      blurb: "适合展示时间趋势、多序列对比，以及连续变化的业务指标。",
      tags: ["平滑", "拐点", "连接空值", "dataset + encode"],
      fields: {
        smooth: "平滑曲线",
        showSymbol: "显示拐点",
        connectNulls: "连接空值",
        showLabel: "显示标签",
        symbol: "拐点形状",
        symbolSize: "拐点大小",
        lineStyleType: "线条样式",
        lineWidth: "线条宽度",
        labelFontSize: "标签字号",
        labelColor: "标签颜色",
      },
      options: {
        symbol: { circle: "圆形", rect: "方形", triangle: "三角形", diamond: "菱形" },
        lineStyleType: { solid: "实线", dashed: "虚线", dotted: "点线" },
      },
      templates: {
        series: {
          label: "系列数据",
          help: "直接使用 `xAxis.data` 和 `series[].data` 的类目数据结构。",
        },
        dataset: {
          label: "Dataset + Encode",
          help: "使用表格型 `dataset.source`，并通过 `encode` 共享映射。",
        },
      },
    },
    bar: {
      label: "柱状图",
      blurb: "适合做类目对比、分组排名、堆叠汇总等场景。",
      tags: ["横向", "排名", "dataset + encode"],
      fields: {
        horizontal: "横向布局",
        showLabel: "显示标签",
        barGap: "柱间距",
        labelPosition: "标签位置",
        labelFontSize: "标签字号",
        labelColor: "标签颜色",
        itemOpacity: "柱透明度",
        borderRadius: "圆角半径",
        borderWidth: "描边宽度",
        borderColor: "描边颜色",
      },
      options: {
        labelPosition: {
          top: "顶部",
          inside: "内部",
          insideTop: "内部顶部",
          insideRight: "内部右侧",
          outside: "外部",
        },
      },
      templates: {
        series: {
          label: "系列数据",
          help: "使用类目轴数据表达分组柱状图或堆叠柱状图。",
        },
        dataset: {
          label: "Dataset + Encode",
          help: "使用一份共享表格数据驱动多个指标。",
        },
      },
    },
    pie: {
      label: "饼图",
      blurb: "适合表达简单占比关系，也支持环图和南丁格尔玫瑰图。",
      tags: ["环图", "玫瑰图", "dataset + encode"],
      fields: {
        labelPosition: "标签位置",
        startAngle: "起始角度",
        showLabel: "显示标签",
        labelFontSize: "标签字号",
        labelColor: "标签颜色",
        labelFormatter: "标签格式",
        labelLineShow: "显示引导线",
        labelLineColor: "引导线颜色",
        labelLineWidth: "引导线宽度",
        itemOpacity: "扇区透明度",
        borderWidth: "描边宽度",
        borderColor: "描边颜色",
      },
      options: {
        labelPosition: { outside: "外侧", inside: "内部" },
      },
      templates: {
        series: {
          label: "系列数据",
          help: "使用 `series[0].data` 中的 name/value 项。",
        },
        dataset: {
          label: "Dataset + Encode",
          help: "使用二维表格，并通过 `encode` 映射名称和值。",
        },
      },
    },
    gauge: {
      label: "仪表盘",
      blurb: "适合展示单个 KPI、进度状态和阈值分段。",
      tags: ["角度", "进度", "标题/明细", "分段"],
      fields: {
        gaugeFoundationGroup: "基础",
        startAngle: "起始角度",
        endAngle: "结束角度",
        progressShow: "显示进度",
        progressWidth: "进度宽度",
        progressColor: "进度颜色",
        gaugeTitleGroup: "仪表名称",
        titleShow: "显示仪表名称",
        titleFontSize: "仪表名称字号",
        titleColor: "仪表名称颜色",
        gaugeDetailGroup: "明细",
        detailShow: "显示明细",
        detailFormatter: "明细格式",
        detailFontSize: "明细字号",
        detailColor: "明细颜色",
        gaugeTicksGroup: "刻度",
        axisWidth: "主环宽度",
        bandStops: "分段颜色",
        axisLabelShow: "显示刻度值",
        axisLabelDistance: "刻度值距离",
        axisLabelFontSize: "刻度值字号",
        axisLabelColor: "刻度值颜色",
        splitLineShow: "显示主刻度线",
        splitLineLength: "主刻度线长度",
        splitLineWidth: "主刻度线宽度",
        splitLineColor: "主刻度线颜色",
        axisTickShow: "显示次刻度线",
        axisTickLength: "次刻度线长度",
        axisTickWidth: "次刻度线宽度",
        axisTickColor: "次刻度线颜色",
        gaugePointerGroup: "指针与圆心",
        pointerShow: "显示指针",
        pointerWidth: "指针宽度",
        pointerColor: "指针颜色",
        anchorShow: "显示圆心点",
        anchorSize: "圆心点大小",
        anchorColor: "圆心点颜色",
      },
      fieldHelp: {
        gaugeFoundationGroup: "控制仪表盘角度、进度环和主环宽度。",
        gaugeTitleGroup: "控制仪表盘内部的小标题样式。",
        gaugeDetailGroup: "控制仪表盘内部的数值明细文本。",
        gaugeTicksGroup: "控制刻度值、主刻度线和次刻度线。",
        gaugePointerGroup: "控制指针和中心圆点的外观。",
      },
      options: {
        pointerWidth: {
          2: "纤细",
          3: "标准",
          4: "稳重",
          5: "醒目",
          6: "粗壮",
        },
        anchorSize: {
          8: "微小",
          12: "小",
          18: "中",
          24: "大",
          32: "超大",
        },
      },
      templates: {
        basic: {
          label: "基础仪表盘",
          help: "使用单个 gauge 系列和一个 KPI 值项。",
        },
      },
    },
    area: {
      label: "面积图",
      blurb: "适合强调趋势变化的体量感，也适合累计感较强的场景。",
      tags: ["面积透明度", "平滑", "渐变", "dataset + encode"],
      fields: {
        smooth: "平滑曲线",
        showSymbol: "显示拐点",
        connectNulls: "连接空值",
        showLabel: "显示标签",
        areaOpacity: "面积透明度",
        areaFillMode: "填充样式",
        symbol: "拐点形状",
        symbolSize: "拐点大小",
        lineStyleType: "线条样式",
        lineWidth: "线条宽度",
        labelFontSize: "标签字号",
        labelColor: "标签颜色",
      },
      options: {
        areaFillMode: { solid: "纯色（自动配色）", gradient: "渐变（自动配色）" },
        symbol: { circle: "圆形", rect: "方形", triangle: "三角形", diamond: "菱形" },
        lineStyleType: { solid: "实线", dashed: "虚线", dotted: "点线" },
      },
      templates: {
        series: {
          label: "系列数据",
          help: "使用带填充的折线系列表达面积图。",
        },
        dataset: {
          label: "Dataset + Encode",
          help: "使用共享数据集表达类目和多个指标。",
        },
      },
    },
    dualAxis: {
      label: "双轴图",
      blurb: "适合双系列混合、两个量纲同时展示的复合场景，左右都可以选择柱或线。",
      tags: ["柱/线组合", "副轴", "dataset + encode"],
      fields: {
        barGap: "柱间距",
        splitLineAxisGroup: "分割线归属",
        splitLineFollowAxis: "分割线跟随",
        leftAxisGroup: "左轴",
        leftAxisLabelFontSize: "左轴字号",
        leftAxisLabelColor: "左轴颜色",
        leftAxisLineShow: "显示左轴线",
        leftAxisLineColor: "左轴线颜色",
        leftAxisTickShow: "显示左轴刻度",
        leftAxisFormatter: "左轴格式",
        leftBarGroup: "左柱",
        leftBarShowLabel: "显示左柱标签",
        leftBarLabelPosition: "左柱标签位置",
        leftBarLabelFontSize: "左柱标签字号",
        leftBarLabelColor: "左柱标签颜色",
        leftBarOpacity: "左柱透明度",
        leftBarGap: "左柱间距",
        leftBarBorderRadius: "左柱圆角半径",
        leftBarBorderWidth: "左柱描边宽度",
        leftBarBorderColor: "左柱描边颜色",
        leftBarColors: "左柱配色",
        leftLineGroup: "左线",
        leftLineSmooth: "左线平滑",
        leftLineArea: "左线带面积",
        leftLineShowSymbol: "显示左线拐点",
        leftLineConnectNulls: "连接左线空值",
        leftLineShowLabel: "显示左线标签",
        leftLineColors: "左线配色",
        leftLineStyleType: "左线样式",
        leftLineWidth: "左线宽度",
        leftLineSymbol: "左线拐点形状",
        leftLineSymbolSize: "左线拐点大小",
        leftLineLabelFontSize: "左线标签字号",
        leftLineLabelColor: "左线标签颜色",
        rightAxisGroup: "右轴",
        rightAxisLabelFontSize: "右轴字号",
        rightAxisLabelColor: "右轴颜色",
        rightAxisLineShow: "显示右轴线",
        rightAxisLineColor: "右轴线颜色",
        rightAxisTickShow: "显示右轴刻度",
        rightAxisFormatter: "右轴格式",
        rightBarGroup: "右柱",
        rightBarShowLabel: "显示右柱标签",
        rightBarLabelPosition: "右柱标签位置",
        rightBarLabelFontSize: "右柱标签字号",
        rightBarLabelColor: "右柱标签颜色",
        rightBarOpacity: "右柱透明度",
        rightBarGap: "右柱间距",
        rightBarBorderRadius: "右柱圆角半径",
        rightBarBorderWidth: "右柱描边宽度",
        rightBarBorderColor: "右柱描边颜色",
        rightBarColors: "右柱配色",
        rightLineGroup: "右线",
        rightLineSmooth: "右线平滑",
        rightLineArea: "右线带面积",
        rightLineShowSymbol: "显示右线拐点",
        rightLineConnectNulls: "连接右线空值",
        rightLineShowLabel: "显示右线标签",
        rightLineColors: "右线配色",
        rightLineStyleType: "右线样式",
        rightLineWidth: "右线宽度",
        rightLineSymbol: "右线拐点形状",
        rightLineSymbolSize: "右线拐点大小",
        rightLineLabelFontSize: "右线标签字号",
        rightLineLabelColor: "右线标签颜色",
      },
      options: {
        splitLineFollowAxis: { left: "左轴", right: "右轴" },
        leftBarLabelPosition: { top: "顶部", inside: "内部", insideTop: "内部顶部", insideRight: "内部右侧", outside: "外部" },
        rightBarLabelPosition: { top: "顶部", inside: "内部", insideTop: "内部顶部", insideRight: "内部右侧", outside: "外部" },
        leftLineStyleType: { solid: "实线", dashed: "虚线", dotted: "点线" },
        rightLineStyleType: { solid: "实线", dashed: "虚线", dotted: "点线" },
        leftLineSymbol: { circle: "圆形", rect: "方形", triangle: "三角形", diamond: "菱形" },
        rightLineSymbol: { circle: "圆形", rect: "方形", triangle: "三角形", diamond: "菱形" },
      },
      templates: {
        series: {
          label: "柱线组合",
          help: "使用类目数据表达左轴柱状图和右轴折线。",
        },
        doubleBar: {
          label: "双柱组合",
          help: "使用类目数据表达左右两侧都为柱状图的双轴图。",
        },
        doubleLine: {
          label: "双线组合",
          help: "使用类目数据表达左右两侧都为折线图的双轴图。",
        },
        dataset: {
          label: "Dataset + Encode",
          help: "使用一张表同时驱动柱状图和折线图。",
        },
      },
    },
    scatter: {
      label: "散点图",
      blurb: "适合做相关性分析、聚类观察和数值轴上的点分布对比。",
      tags: ["散点", "数值轴", "dataset + encode"],
      fields: {
        showLabel: "显示标签",
        symbolSize: "默认点大小",
        symbol: "点形状",
        itemOpacity: "点透明度",
        borderWidth: "描边宽度",
        borderColor: "描边颜色",
        labelFontSize: "标签字号",
        labelColor: "标签颜色",
      },
      options: {
        symbolSize: {
          24: "很小",
          40: "小",
          64: "中",
          88: "大",
          116: "很大",
        },
        symbol: { circle: "圆形", rect: "方形", triangle: "三角形", diamond: "菱形" },
      },
      templates: {
        series: {
          label: "散点系列",
          help: "使用数值型 `[x, y]` 点位表达多系列散点图。",
        },
        dataset: {
          label: "Dataset + Encode",
          help: "使用共享表格数据，并通过 `encode` 建立映射。",
        },
      },
    },
    radar: {
      label: "雷达图",
      blurb: "适合展示多维评分、能力画像和均衡度对比。",
      tags: ["形状", "分割区域", "标签", "面积填充"],
      fields: {
        radarFoundationGroup: "基础",
        shape: "形状",
        splitNumber: "分割段数",
        showSymbol: "显示拐点",
        showLabel: "显示标签",
        labelFormatter: "标签格式",
        areaOpacity: "面积透明度",
        radarGridGroup: "网格与轴线",
        splitLineColor: "分割线颜色",
        splitLineWidth: "分割线宽度",
        splitLineType: "分割线样式",
        axisLineColor: "轴线颜色",
        axisLineWidth: "轴线宽度",
        axisLineType: "轴线样式",
        axisNameFontSize: "维度名字号",
        axisNameColor: "维度名颜色",
        axisNameBold: "维度名加粗",
        radarSeriesGroup: "数据面样式",
        symbol: "拐点形状",
        symbolSize: "拐点大小",
        lineStyleType: "线条样式",
        lineWidth: "线条宽度",
        labelFontSize: "标签字号",
        labelColor: "标签颜色",
      },
      fieldHelp: {
        radarFoundationGroup: "控制雷达图形状、分割段数和标签基础能力。",
        radarGridGroup: "控制分割线、轴线以及维度名样式。",
        radarSeriesGroup: "控制雷达图数据面的拐点、描边和标签样式。",
      },
      options: {
        shape: { polygon: "多边形", circle: "圆形" },
        symbol: { circle: "圆形", rect: "方形", triangle: "三角形", diamond: "菱形" },
        lineStyleType: { solid: "实线", dashed: "虚线", dotted: "点线" },
        splitLineType: { solid: "实线", dashed: "虚线", dotted: "点线" },
        axisLineType: { solid: "实线", dashed: "虚线", dotted: "点线" },
      },
      templates: {
        basic: {
          label: "雷达数据",
          help: "使用 radar indicator 和多组对比数值数组。",
        },
      },
    },
    funnel: {
      label: "漏斗图",
      blurb: "适合展示阶段转化、流程流失和有序业务漏斗。",
      tags: ["排序", "间隔", "标签位置", "dataset + encode"],
      fields: {
        funnelBaseGroup: "基础",
        sort: "排序方式",
        gap: "间隔",
        minSize: "最小尺寸",
        maxSize: "最大尺寸",
        itemOpacity: "漏斗透明度",
        funnelLabelGroup: "标签",
        labelPosition: "标签位置",
        showLabel: "显示标签",
        labelFormatter: "标签格式",
        labelFontSize: "标签字号",
        labelColor: "标签颜色",
        left: "左侧位置",
        top: "顶部位置",
        width: "宽度",
        height: "高度",
      },
      fieldHelp: {
        funnelBaseGroup: "控制排序方向、间隔以及整体宽度范围。",
        funnelLabelGroup: "控制标签显示、位置、格式和文字样式。",
      },
      options: {
        sort: { descending: "降序", ascending: "升序", none: "保持输入顺序" },
        labelPosition: { outside: "外侧", inside: "内部" },
      },
      templates: {
        series: {
          label: "系列数据",
          help: "使用有序阶段 name/value 项表达漏斗图。",
        },
        dataset: {
          label: "Dataset + Encode",
          help: "使用二维表格，并显式映射 stage/value。",
        },
      },
    },
  },
};

const CHART_DEFINITIONS = {
  line: {
    label: "Line",
    asset: `${SKILL_STATIC_ROOT}/line.png`,
    blurb: "Best for trends over time, multiple series comparison, and continuity-focused metrics.",
    tags: ["smooth", "symbols", "connectNulls", "dataset + encode"],
    fields: [
      { id: "smooth", label: "Smooth", type: "checkbox", default: true },
      { id: "showSymbol", label: "Show Symbols", type: "checkbox", default: true },
      { id: "connectNulls", label: "Connect Nulls", type: "checkbox", default: false },
      { id: "showLabel", label: "Show Labels", type: "checkbox", default: true },
      {
        id: "symbol",
        label: "Symbol",
        type: "select",
        default: "circle",
        options: [
          ["circle", "Circle"],
          ["rect", "Rect"],
          ["triangle", "Triangle"],
          ["diamond", "Diamond"],
        ],
      },
      { id: "symbolSize", label: "Symbol Size", type: "number", default: 5, step: 1 },
      {
        id: "lineStyleType",
        label: "Line Style",
        type: "select",
        default: "solid",
        options: [
          ["solid", "Solid"],
          ["dashed", "Dashed"],
          ["dotted", "Dotted"],
        ],
      },
      { id: "lineWidth", label: "Line Width", type: "number", default: 3, step: 0.2 },
      { id: "labelFontSize", label: "Label Size", type: "number", default: 10, step: 1 },
      { id: "labelColor", label: "Label Color", type: "color", default: "#334155" },
    ],
    templates: [
      {
        id: "series",
        label: "Series Data",
        help: "Use direct category data with `xAxis.data` and `series[].data`.",
        data: {
          xAxis: { data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] },
          yAxis: {},
          series: [
            { type: "line", name: "Visits", data: [120, 132, 101, 134, 90, 230] },
            { type: "line", name: "Orders", data: [32, 41, 38, 52, 49, 68] },
          ],
        },
      },
      {
        id: "dataset",
        label: "Dataset + Encode",
        help: "Use tabular `dataset.source` with shared encode fields.",
        data: {
          dataset: {
            source: [
              ["day", "visits", "orders"],
              ["Mon", 120, 32],
              ["Tue", 132, 41],
              ["Wed", 101, 38],
              ["Thu", 134, 52],
              ["Fri", 90, 49],
              ["Sat", 230, 68],
            ],
          },
          xAxis: { type: "category" },
          yAxis: { type: "value" },
          series: [
            { type: "line", name: "Visits", encode: { x: "day", y: "visits" } },
            { type: "line", name: "Orders", encode: { x: "day", y: "orders" } },
          ],
        },
      },
    ],
  },
  bar: {
    label: "Bar",
    asset: `${SKILL_STATIC_ROOT}/bar.png`,
    blurb: "Best for category comparison, grouped bars, ranking, and stacked totals.",
    tags: ["horizontal", "ranking", "dataset + encode"],
    fields: [
      { id: "showLabel", label: "Show Labels", type: "checkbox", default: true },
      { id: "barGap", label: "Bar Gap", type: "text", default: "10%" },
      {
        id: "labelPosition",
        label: "Label Position",
        type: "select",
        default: "top",
        options: [
          ["top", "Top"],
          ["inside", "Inside"],
          ["insideTop", "Inside Top"],
          ["insideRight", "Inside Right"],
          ["outside", "Outside"],
        ],
      },
      { id: "labelFontSize", label: "Label Size", type: "number", default: 10, step: 1 },
      { id: "labelColor", label: "Label Color", type: "color", default: "#334155" },
      { id: "itemOpacity", label: "Bar Opacity", type: "number", default: 0.92, step: 0.05 },
      { id: "borderRadius", label: "Corner Radius", type: "number", default: 0, step: 0.5 },
      { id: "borderWidth", label: "Border Width", type: "number", default: 0, step: 0.5 },
      { id: "borderColor", label: "Border Color", type: "color", default: "#ffffff" },
    ],
    templates: [
      {
        id: "series",
        label: "Series Data",
        help: "Use category data for grouped or stacked bars.",
        data: {
          xAxis: { data: ["Q1", "Q2", "Q3", "Q4"] },
          yAxis: {},
          series: [
            { type: "bar", name: "Revenue", data: [320, 410, 505, 620] },
            { type: "bar", name: "Cost", data: [180, 240, 290, 330] },
          ],
        },
      },
      {
        id: "dataset",
        label: "Dataset + Encode",
        help: "Use one shared tabular dataset with multiple metrics.",
        data: {
          dataset: {
            source: [
              ["quarter", "revenue", "cost"],
              ["Q1", 320, 180],
              ["Q2", 410, 240],
              ["Q3", 505, 290],
              ["Q4", 620, 330],
            ],
          },
          xAxis: { type: "category" },
          yAxis: { type: "value" },
          series: [
            { type: "bar", name: "Revenue", encode: { x: "quarter", y: "revenue" } },
            { type: "bar", name: "Cost", encode: { x: "quarter", y: "cost" } },
          ],
        },
      },
    ],
  },
  pie: {
    label: "Pie",
    asset: `${SKILL_STATIC_ROOT}/pie-basic.png`,
    blurb: "Best for simple part-to-whole storytelling with optional donut or rose variants.",
    tags: ["donut", "rose", "dataset + encode"],
    fields: [
      {
        id: "labelPosition",
        label: "Label Position",
        type: "select",
        default: "outside",
        options: [
          ["outside", "Outside"],
          ["inside", "Inside"],
        ],
      },
      { id: "startAngle", label: "Start Angle", type: "number", default: 90 },
      { id: "showLabel", label: "Show Labels", type: "checkbox", default: true },
      { id: "labelFontSize", label: "Label Size", type: "number", default: 11, step: 1 },
      { id: "labelColor", label: "Label Color", type: "color", default: "#334155" },
      { id: "labelFormatter", label: "Label Formatter", type: "text", default: "{b} {d}%" },
      { id: "labelLineShow", label: "Show Label Line", type: "checkbox", default: true },
      { id: "labelLineColor", label: "Label Line Color", type: "color", default: "#94a3b8" },
      { id: "labelLineWidth", label: "Label Line Width", type: "number", default: 0.8, step: 0.1 },
      { id: "itemOpacity", label: "Slice Opacity", type: "number", default: 0.96, step: 0.05 },
      { id: "borderWidth", label: "Border Width", type: "number", default: 0, step: 0.5 },
      { id: "borderColor", label: "Border Color", type: "color", default: "#ffffff" },
    ],
    templates: [
      {
        id: "series",
        label: "Series Data",
        help: "Use `series[0].data` items with name and value.",
        data: {
          series: [
            {
              type: "pie",
              data: [
                { name: "Search", value: 1048 },
                { name: "Email", value: 735 },
                { name: "Direct", value: 580 },
                { name: "Ads", value: 484 },
                { name: "Video", value: 300 },
              ],
            },
          ],
        },
      },
      {
        id: "dataset",
        label: "Dataset + Encode",
        help: "Use a table and map itemName/value through encode.",
        data: {
          dataset: {
            source: [
              ["channel", "value"],
              ["Search", 1048],
              ["Email", 735],
              ["Direct", 580],
              ["Ads", 484],
              ["Video", 300],
            ],
          },
          series: [
            { type: "pie", encode: { itemName: "channel", value: "value" } },
          ],
        },
      },
    ],
  },
  gauge: {
    label: "Gauge",
    asset: `${SKILL_STATIC_ROOT}/gauge.png`,
    blurb: "Best for a single KPI, progress-like states, and segmented threshold displays.",
    tags: ["angles", "progress", "title/detail", "segments"],
    fields: [
      { id: "gaugeFoundationGroup", label: "Foundation", type: "group", help: "Control gauge angles and progress ring." },
      { id: "startAngle", label: "Start Angle", type: "number", default: 225 },
      { id: "endAngle", label: "End Angle", type: "number", default: -45 },
      { id: "progressShow", label: "Show Progress", type: "checkbox", default: true },
      { id: "progressWidth", label: "Progress Width", type: "number", default: 20, step: 1 },
      { id: "progressColor", label: "Progress Color", type: "color", default: "#5470c6" },
      { id: "axisWidth", label: "Band Width", type: "number", default: 20, step: 1 },
      {
        id: "bandStops",
        label: "Segment Colors",
        type: "text",
        default: "#22c55e, #84cc16, #facc15, #f97316, #ef4444",
      },
      { id: "gaugeTitleGroup", label: "Gauge Name", type: "group", help: "Control the small title inside the gauge." },
      { id: "titleShow", label: "Show Gauge Name", type: "checkbox", default: true },
      { id: "titleFontSize", label: "Gauge Name Size", type: "number", default: 12, step: 1 },
      { id: "titleColor", label: "Gauge Name Color", type: "color", default: "#6e7079" },
      { id: "gaugeDetailGroup", label: "Detail", type: "group", help: "Control the value detail text inside the gauge." },
      { id: "detailShow", label: "Show Detail", type: "checkbox", default: true },
      { id: "detailFormatter", label: "Detail Formatter", type: "text", default: "{value}%" },
      { id: "detailFontSize", label: "Detail Size", type: "number", default: 22, step: 1 },
      { id: "detailColor", label: "Detail Color", type: "color", default: "#464646" },
      { id: "gaugeTicksGroup", label: "Ticks", type: "group", help: "Control scale labels and tick marks." },
      { id: "axisLabelShow", label: "Show Axis Labels", type: "checkbox", default: true },
      { id: "axisLabelDistance", label: "Axis Label Distance", type: "number", default: 25, step: 1 },
      { id: "axisLabelFontSize", label: "Axis Label Size", type: "number", default: 10, step: 1 },
      { id: "axisLabelColor", label: "Axis Label Color", type: "color", default: "#6e7079" },
      { id: "splitLineShow", label: "Show Major Ticks", type: "checkbox", default: true },
      { id: "splitLineLength", label: "Major Tick Length", type: "number", default: 12, step: 1 },
      { id: "splitLineWidth", label: "Major Tick Width", type: "number", default: 2, step: 0.5 },
      { id: "splitLineColor", label: "Major Tick Color", type: "color", default: "#6e7079" },
      { id: "axisTickShow", label: "Show Minor Ticks", type: "checkbox", default: true },
      { id: "axisTickLength", label: "Minor Tick Length", type: "number", default: 6, step: 1 },
      { id: "axisTickWidth", label: "Minor Tick Width", type: "number", default: 1, step: 0.5 },
      { id: "axisTickColor", label: "Minor Tick Color", type: "color", default: "#999999" },
      { id: "gaugePointerGroup", label: "Pointer And Anchor", type: "group", help: "Control pointer and center anchor appearance." },
      { id: "pointerShow", label: "Show Pointer", type: "checkbox", default: true },
      {
        id: "pointerWidth",
        label: "Pointer Width",
        type: "select",
        default: "4",
        options: [
          ["2", "Slim"],
          ["3", "Standard"],
          ["4", "Balanced"],
          ["5", "Bold"],
          ["6", "Heavy"],
        ],
      },
      { id: "pointerColor", label: "Pointer Color", type: "color", default: "#2f4554" },
      { id: "anchorShow", label: "Show Anchor", type: "checkbox", default: true },
      {
        id: "anchorSize",
        label: "Anchor Size",
        type: "select",
        default: "20",
        options: [
          ["8", "Tiny"],
          ["12", "Small"],
          ["20", "Medium"],
          ["24", "Large"],
          ["32", "XL"],
        ],
      },
      { id: "anchorColor", label: "Anchor Color", type: "color", default: "#2f4554" },
    ],
    templates: [
      {
        id: "basic",
        label: "Basic Gauge",
        help: "Use one gauge series with one KPI value item.",
        data: {
          series: [
            {
              type: "gauge",
              data: [{ value: 68, name: "Completion" }],
            },
          ],
        },
      },
    ],
  },
  area: {
    label: "Area",
    asset: `${SKILL_STATIC_ROOT}/area.png`,
    blurb: "Best for trend comparison when filled volume or cumulative feel matters.",
    tags: ["area opacity", "smooth", "gradient", "dataset + encode"],
    fields: [
      { id: "smooth", label: "Smooth", type: "checkbox", default: true },
      { id: "showSymbol", label: "Show Symbols", type: "checkbox", default: true },
      {
        id: "symbol",
        label: "Symbol",
        type: "select",
        default: "circle",
        options: [
          ["circle", "Circle"],
          ["rect", "Rect"],
          ["triangle", "Triangle"],
          ["diamond", "Diamond"],
        ],
      },
      { id: "symbolSize", label: "Symbol Size", type: "number", default: 4, step: 1 },
      { id: "connectNulls", label: "Connect Nulls", type: "checkbox", default: false },
      { id: "showLabel", label: "Show Labels", type: "checkbox", default: true },
      { id: "areaOpacity", label: "Area Opacity", type: "number", default: 0.35, step: 0.05 },
      {
        id: "areaFillMode",
        label: "Fill Style",
        type: "select",
        default: "gradient",
        options: [
          ["solid", "Solid (Auto Palette)"],
          ["gradient", "Gradient (Auto Palette)"],
        ],
      },
      {
        id: "lineStyleType",
        label: "Line Style",
        type: "select",
        default: "solid",
        options: [
          ["solid", "Solid"],
          ["dashed", "Dashed"],
          ["dotted", "Dotted"],
        ],
      },
      { id: "lineWidth", label: "Line Width", type: "number", default: 2, step: 0.2 },
      { id: "labelFontSize", label: "Label Size", type: "number", default: 10, step: 1 },
      { id: "labelColor", label: "Label Color", type: "color", default: "#334155" },
    ],
    templates: [
      {
        id: "series",
        label: "Series Data",
        help: "Use filled line series against category data.",
        data: {
          xAxis: { data: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"] },
          yAxis: {},
          series: [
            { type: "line", name: "Signups", data: [120, 182, 191, 234, 290, 330] },
            { type: "line", name: "Active", data: [80, 132, 151, 174, 220, 260] },
          ],
        },
      },
      {
        id: "dataset",
        label: "Dataset + Encode",
        help: "Use a shared dataset with category and multiple metrics.",
        data: {
          dataset: {
            source: [
              ["month", "signups", "active"],
              ["Jan", 120, 80],
              ["Feb", 182, 132],
              ["Mar", 191, 151],
              ["Apr", 234, 174],
              ["May", 290, 220],
              ["Jun", 330, 260],
            ],
          },
          xAxis: { type: "category" },
          yAxis: { type: "value" },
          series: [
            { type: "line", name: "Signups", encode: { x: "month", y: "signups" } },
            { type: "line", name: "Active", encode: { x: "month", y: "active" } },
          ],
        },
      },
    ],
  },
  dualAxis: {
    label: "Dual-Axis",
    asset: `${SKILL_STATIC_ROOT}/dual-axis.png`,
    blurb: "Best for mixed two-series layouts when two units must coexist in one chart. Each side can be a bar or a line.",
    tags: ["bar/line mix", "secondary axis", "dataset + encode"],
      fields: [
      { id: "splitLineAxisGroup", label: "Split Line Binding", type: "group", help: "Choose which value axis the shared split lines follow." },
      {
        id: "splitLineFollowAxis",
        label: "Split Line Follow",
        type: "select",
        default: "left",
        options: [
          ["left", "Left Axis"],
          ["right", "Right Axis"],
        ],
      },
      { id: "leftAxisGroup", label: "Left Value Axis", type: "group", help: "Control the bar axis scale, labels, ticks, and line styling." },
      { id: "leftAxisLabelFontSize", label: "Left Axis Label Size", type: "number", default: 11, step: 1 },
      { id: "leftAxisLabelColor", label: "Left Axis Label Color", type: "color", default: "#9ca3af" },
      { id: "leftAxisLineShow", label: "Show Left Axis Line", type: "checkbox", default: true },
      { id: "leftAxisLineColor", label: "Left Axis Line Color", type: "color", default: "#9ca3af" },
      { id: "leftAxisTickShow", label: "Show Left Axis Ticks", type: "checkbox", default: true },
      { id: "leftAxisFormatter", label: "Left Axis Formatter", type: "text", default: "{value}" },
      { id: "leftBarGroup", label: "Left Bar", type: "group", help: "Bar-style controls for the left series." },
      { id: "leftBarShowLabel", label: "Show Left Bar Labels", type: "checkbox", default: true },
      {
        id: "leftBarLabelPosition",
        label: "Left Bar Label Position",
        type: "select",
        default: "top",
        options: [
          ["top", "Top"],
          ["inside", "Inside"],
          ["insideTop", "Inside Top"],
          ["insideRight", "Inside Right"],
          ["outside", "Outside"],
        ],
      },
      { id: "leftBarLabelFontSize", label: "Left Bar Label Size", type: "number", default: 10, step: 1 },
      { id: "leftBarLabelColor", label: "Left Bar Label Color", type: "color", default: "#334155" },
      { id: "leftBarOpacity", label: "Left Bar Opacity", type: "number", default: 0.92, step: 0.05 },
      { id: "leftBarGap", label: "Left Bar Gap", type: "text", default: "10%" },
      { id: "leftBarBorderRadius", label: "Left Bar Corner Radius", type: "number", default: 0, step: 0.5 },
      { id: "leftBarBorderWidth", label: "Left Bar Border Width", type: "number", default: 0, step: 0.5 },
      { id: "leftBarBorderColor", label: "Left Bar Border Color", type: "color", default: "#ffffff" },
      { id: "leftBarColors", label: "Left Bar Palette", type: "text", default: "#5470c6, #73c0de, #91cc75" },
      { id: "leftLineGroup", label: "Left Line", type: "group", help: "Line-style controls for the left series." },
      { id: "leftLineSmooth", label: "Smooth Left Line", type: "checkbox", default: true },
      { id: "leftLineArea", label: "Left Line With Area", type: "checkbox", default: false },
      { id: "leftLineShowSymbol", label: "Show Left Symbols", type: "checkbox", default: false },
      { id: "leftLineConnectNulls", label: "Connect Left Nulls", type: "checkbox", default: false },
      { id: "leftLineShowLabel", label: "Show Left Line Labels", type: "checkbox", default: false },
      { id: "leftLineColors", label: "Left Line Palette", type: "text", default: "#5470c6, #3b82f6, #06b6d4" },
      {
        id: "leftLineStyleType",
        label: "Left Line Style",
        type: "select",
        default: "solid",
        options: [
          ["solid", "Solid"],
          ["dashed", "Dashed"],
          ["dotted", "Dotted"],
        ],
      },
      { id: "leftLineWidth", label: "Left Line Width", type: "number", default: 3, step: 0.2 },
      {
        id: "leftLineSymbol",
        label: "Left Symbol",
        type: "select",
        default: "circle",
        options: [
          ["circle", "Circle"],
          ["rect", "Rect"],
          ["triangle", "Triangle"],
          ["diamond", "Diamond"],
        ],
      },
      { id: "leftLineSymbolSize", label: "Left Symbol Size", type: "number", default: 5, step: 1 },
      { id: "leftLineLabelFontSize", label: "Left Line Label Size", type: "number", default: 10, step: 1 },
      { id: "leftLineLabelColor", label: "Left Line Label Color", type: "color", default: "#334155" },
      { id: "rightAxisGroup", label: "Right Value Axis", type: "group", help: "Control the right value axis scale, labels, ticks, and line styling." },
      { id: "rightAxisLabelFontSize", label: "Right Axis Label Size", type: "number", default: 11, step: 1 },
      { id: "rightAxisLabelColor", label: "Right Axis Label Color", type: "color", default: "#9ca3af" },
      { id: "rightAxisLineShow", label: "Show Right Axis Line", type: "checkbox", default: true },
      { id: "rightAxisLineColor", label: "Right Axis Line Color", type: "color", default: "#9ca3af" },
      { id: "rightAxisTickShow", label: "Show Right Axis Ticks", type: "checkbox", default: true },
      { id: "rightAxisFormatter", label: "Right Axis Formatter", type: "text", default: "{value}" },
      { id: "rightBarGroup", label: "Right Bar", type: "group", help: "Bar-style controls for the right series." },
      { id: "rightBarShowLabel", label: "Show Right Bar Labels", type: "checkbox", default: true },
      {
        id: "rightBarLabelPosition",
        label: "Right Bar Label Position",
        type: "select",
        default: "top",
        options: [
          ["top", "Top"],
          ["inside", "Inside"],
          ["insideTop", "Inside Top"],
          ["insideRight", "Inside Right"],
          ["outside", "Outside"],
        ],
      },
      { id: "rightBarLabelFontSize", label: "Right Bar Label Size", type: "number", default: 10, step: 1 },
      { id: "rightBarLabelColor", label: "Right Bar Label Color", type: "color", default: "#334155" },
      { id: "rightBarOpacity", label: "Right Bar Opacity", type: "number", default: 0.92, step: 0.05 },
      { id: "rightBarGap", label: "Right Bar Gap", type: "text", default: "10%" },
      { id: "rightBarBorderRadius", label: "Right Bar Corner Radius", type: "number", default: 0, step: 0.5 },
      { id: "rightBarBorderWidth", label: "Right Bar Border Width", type: "number", default: 0, step: 0.5 },
      { id: "rightBarBorderColor", label: "Right Bar Border Color", type: "color", default: "#ffffff" },
      { id: "rightBarColors", label: "Right Bar Palette", type: "text", default: "#ef4444, #f97316, #f59e0b" },
      { id: "rightLineGroup", label: "Right Line", type: "group", help: "Line-style controls for the right series." },
      { id: "rightLineSmooth", label: "Smooth Right Line", type: "checkbox", default: true },
      { id: "rightLineArea", label: "Right Line With Area", type: "checkbox", default: false },
      { id: "rightLineShowSymbol", label: "Show Right Symbols", type: "checkbox", default: false },
      { id: "rightLineConnectNulls", label: "Connect Right Nulls", type: "checkbox", default: false },
      { id: "rightLineShowLabel", label: "Show Right Line Labels", type: "checkbox", default: false },
      { id: "rightLineColors", label: "Right Line Palette", type: "text", default: "#ef4444, #f97316, #f59e0b" },
      {
        id: "rightLineStyleType",
        label: "Right Line Style",
        type: "select",
        default: "solid",
        options: [
          ["solid", "Solid"],
          ["dashed", "Dashed"],
          ["dotted", "Dotted"],
        ],
      },
      { id: "rightLineWidth", label: "Right Line Width", type: "number", default: 3, step: 0.2 },
      {
        id: "rightLineSymbol",
        label: "Right Symbol",
        type: "select",
        default: "circle",
        options: [
          ["circle", "Circle"],
          ["rect", "Rect"],
          ["triangle", "Triangle"],
          ["diamond", "Diamond"],
        ],
      },
      { id: "rightLineSymbolSize", label: "Right Symbol Size", type: "number", default: 5, step: 1 },
      { id: "rightLineLabelFontSize", label: "Right Label Size", type: "number", default: 10, step: 1 },
      { id: "rightLineLabelColor", label: "Right Label Color", type: "color", default: "#334155" },
    ],
    templates: [
      {
        id: "series",
        label: "Two Bars + Line",
        help: "Use category data with two left-axis bars and one right-axis line.",
        data: {
          xAxis: { data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] },
          yAxis: [{ name: "Volume" }, { name: "Rate" }],
          series: [
            { type: "bar", name: "Sales", yAxisIndex: 0, data: [320, 332, 301, 334, 390, 330] },
            { type: "bar", name: "Orders", yAxisIndex: 0, data: [210, 226, 198, 245, 278, 256] },
            { type: "line", name: "Rate", yAxisIndex: 1, data: [10, 12, 9, 14, 18, 16] },
          ],
        },
      },
      {
        id: "doubleBar",
        label: "Bar + Bar",
        help: "Use category data with left and right series both rendered as bars.",
        data: {
          xAxis: { data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] },
          yAxis: [{ name: "Sales" }, { name: "Target" }],
          series: [
            { type: "bar", name: "Sales", data: [320, 332, 301, 334, 390, 330] },
            { type: "bar", name: "Target", data: [280, 300, 315, 340, 360, 320] },
          ],
        },
      },
      {
        id: "doubleLine",
        label: "Line + Line",
        help: "Use category data with left and right series both rendered as lines.",
        data: {
          xAxis: { data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat"] },
          yAxis: [{ name: "Sales" }, { name: "Rate" }],
          series: [
            { type: "line", name: "Sales", data: [320, 332, 301, 334, 390, 330] },
            { type: "line", name: "Rate", data: [10, 12, 9, 14, 18, 16] },
          ],
        },
      },
      {
        id: "dataset",
        label: "Dataset + Encode",
        help: "Use one table to drive two left-axis bars and one right-axis line.",
        data: {
          dataset: {
            source: [
              ["day", "sales", "orders", "rate"],
              ["Mon", 320, 210, 10],
              ["Tue", 332, 226, 12],
              ["Wed", 301, 198, 9],
              ["Thu", 334, 245, 14],
              ["Fri", 390, 278, 18],
              ["Sat", 330, 256, 16],
            ],
          },
          xAxis: { type: "category" },
          yAxis: [{ type: "value", name: "Volume" }, { type: "value", name: "Rate" }],
          series: [
            { type: "bar", name: "Sales", yAxisIndex: 0, encode: { x: "day", y: "sales" } },
            { type: "bar", name: "Orders", yAxisIndex: 0, encode: { x: "day", y: "orders" } },
            { type: "line", name: "Rate", yAxisIndex: 1, encode: { x: "day", y: "rate" } },
          ],
        },
      },
    ],
  },
  scatter: {
    label: "Scatter",
    asset: `${SKILL_STATIC_ROOT}/scatter-basic.png`,
    blurb: "Best for correlation, clusters, and point distributions on value axes.",
    tags: ["scatter", "value axes", "dataset + encode"],
    fields: [
      { id: "showLabel", label: "Show Labels", type: "checkbox", default: false },
      {
        id: "symbolSize",
        label: "Default Symbol Size",
        type: "number",
        default: 64,
        min: 1,
        step: 1,
      },
      {
        id: "symbol",
        label: "Symbol",
        type: "select",
        default: "circle",
        options: [
          ["circle", "Circle"],
          ["rect", "Rect"],
          ["triangle", "Triangle"],
          ["diamond", "Diamond"],
        ],
      },
      { id: "itemOpacity", label: "Point Opacity", type: "number", default: 0.92, step: 0.05 },
      { id: "borderWidth", label: "Border Width", type: "number", default: 0, step: 0.5 },
      { id: "borderColor", label: "Border Color", type: "color", default: "#ffffff" },
      { id: "labelFontSize", label: "Label Size", type: "number", default: 10, step: 1 },
      { id: "labelColor", label: "Label Color", type: "color", default: "#334155" },
    ],
    templates: [
      {
        id: "series",
        label: "Scatter Series",
        help: "Use numeric `[x, y]` points for multi-series scatter.",
        data: {
          xAxis: { type: "value", name: "Spend" },
          yAxis: { type: "value", name: "Revenue" },
          series: [
            { type: "scatter", name: "North", data: [[10, 18], [14, 22], [18, 28], [22, 34]] },
            { type: "scatter", name: "South", data: [[9, 12], [13, 17], [20, 25], [26, 31]] },
          ],
        },
      },
      {
        id: "dataset",
        label: "Dataset + Encode",
        help: "Use a shared table with encode mappings.",
        data: {
          dataset: {
            source: [
              ["spend", "north", "south"],
              [10, 18, 12],
              [14, 22, 17],
              [18, 28, 25],
              [22, 34, 31],
            ],
          },
          xAxis: { type: "value" },
          yAxis: { type: "value" },
          series: [
            { type: "scatter", name: "North", encode: { x: "spend", y: "north" } },
            { type: "scatter", name: "South", encode: { x: "spend", y: "south" } },
          ],
        },
      },
    ],
  },
  radar: {
    label: "Radar",
    asset: `${SKILL_STATIC_ROOT}/radar.png`,
    blurb: "Best for multi-dimension scoring, balanced comparisons, and capability profiles.",
    tags: ["shape", "split area", "labels", "area fill"],
    fields: [
      { id: "radarFoundationGroup", label: "Foundation", type: "group", help: "Control radar shape and split count." },
      {
        id: "shape",
        label: "Shape",
        type: "select",
        default: "polygon",
        options: [
          ["polygon", "Polygon"],
          ["circle", "Circle"],
        ],
      },
      { id: "splitNumber", label: "Split Number", type: "number", default: 5 },
      { id: "showSymbol", label: "Show Symbols", type: "checkbox", default: true },
      { id: "showLabel", label: "Show Labels", type: "checkbox", default: false },
      { id: "labelFormatter", label: "Label Formatter", type: "text", default: "{b}: {c}" },
      { id: "areaOpacity", label: "Area Opacity", type: "number", default: 0.18, step: 0.05 },
      { id: "radarGridGroup", label: "Grid Lines", type: "group", help: "Control split lines and axis lines." },
      { id: "splitLineColor", label: "Split Line Color", type: "color", default: "#d0d7de" },
      { id: "splitLineWidth", label: "Split Line Width", type: "number", default: 0.8, step: 0.1 },
      {
        id: "splitLineType",
        label: "Split Line Style",
        type: "select",
        default: "solid",
        options: [
          ["solid", "Solid"],
          ["dashed", "Dashed"],
          ["dotted", "Dotted"],
        ],
      },
      { id: "axisLineColor", label: "Axis Line Color", type: "color", default: "#94a3b8" },
      { id: "axisLineWidth", label: "Axis Line Width", type: "number", default: 1, step: 0.1 },
      {
        id: "axisLineType",
        label: "Axis Line Style",
        type: "select",
        default: "solid",
        options: [
          ["solid", "Solid"],
          ["dashed", "Dashed"],
          ["dotted", "Dotted"],
        ],
      },
      { id: "axisNameFontSize", label: "Axis Name Size", type: "number", default: 11, step: 1 },
      { id: "axisNameColor", label: "Axis Name Color", type: "color", default: "#334155" },
      { id: "axisNameBold", label: "Bold Axis Names", type: "checkbox", default: true },
      { id: "radarSeriesGroup", label: "Series Style", type: "group", help: "Control symbol and outline style for radar series." },
      {
        id: "symbol",
        label: "Symbol",
        type: "select",
        default: "circle",
        options: [
          ["circle", "Circle"],
          ["rect", "Rect"],
          ["triangle", "Triangle"],
          ["diamond", "Diamond"],
        ],
      },
      { id: "symbolSize", label: "Symbol Size", type: "number", default: 5, step: 1 },
      {
        id: "lineStyleType",
        label: "Line Style",
        type: "select",
        default: "solid",
        options: [
          ["solid", "Solid"],
          ["dashed", "Dashed"],
          ["dotted", "Dotted"],
        ],
      },
      { id: "lineWidth", label: "Line Width", type: "number", default: 2.4, step: 0.2 },
      { id: "labelFontSize", label: "Label Size", type: "number", default: 10, step: 1 },
      { id: "labelColor", label: "Label Color", type: "color", default: "#334155" },
    ],
    templates: [
      {
        id: "basic",
        label: "Radar Data",
        help: "Use radar indicators and comparative value arrays.",
        data: {
          radar: {
            indicator: [
              { name: "Quality", max: 100 },
              { name: "Speed", max: 100 },
              { name: "Cost", max: 100 },
              { name: "Scale", max: 100 },
              { name: "Satisfaction", max: 100 },
            ],
          },
          series: [
            {
              type: "radar",
              data: [
                { name: "Team A", value: [90, 82, 70, 88, 91] },
                { name: "Team B", value: [76, 90, 82, 72, 84] },
              ],
            },
          ],
        },
      },
    ],
  },
  funnel: {
    label: "Funnel",
    asset: `${SKILL_STATIC_ROOT}/funnel.png`,
    blurb: "Best for stage conversion, process drop-off, and ordered business pipelines.",
    tags: ["sort", "gap", "label position", "dataset + encode"],
    fields: [
      { id: "funnelBaseGroup", label: "Foundation", type: "group", help: "Control ordering, gap, and width range." },
      {
        id: "sort",
        label: "Sort",
        type: "select",
        default: "descending",
        options: [
          ["descending", "Descending"],
          ["ascending", "Ascending"],
          ["none", "Preserve Input Order"],
        ],
      },
      { id: "gap", label: "Gap", type: "number", default: 4 },
      { id: "minSize", label: "Min Size", type: "text", default: "20%" },
      { id: "maxSize", label: "Max Size", type: "text", default: "80%" },
      { id: "itemOpacity", label: "Funnel Opacity", type: "number", default: 0.92, step: 0.05 },
      { id: "funnelLabelGroup", label: "Labels", type: "group", help: "Control label visibility, placement, formatter, and text style." },
      {
        id: "labelPosition",
        label: "Label Position",
        type: "select",
        default: "outside",
        options: [
          ["outside", "Outside"],
          ["inside", "Inside"],
        ],
      },
      { id: "showLabel", label: "Show Labels", type: "checkbox", default: true },
      { id: "labelFormatter", label: "Label Formatter", type: "text", default: "{b}: {c}" },
      { id: "labelFontSize", label: "Label Size", type: "number", default: 10, step: 1 },
      { id: "labelColor", label: "Label Color", type: "color", default: "#334155" },
    ],
    templates: [
      {
        id: "series",
        label: "Series Data",
        help: "Use ordered stage items with name and value.",
        data: {
          series: [
            {
              type: "funnel",
              data: [
                { name: "Visit", value: 1000 },
                { name: "Sign Up", value: 600 },
                { name: "Qualified", value: 320 },
                { name: "Proposal", value: 180 },
                { name: "Won", value: 96 },
              ],
            },
          ],
        },
      },
      {
        id: "dataset",
        label: "Dataset + Encode",
        help: "Use tabular data with explicit stage/value mapping.",
        data: {
          dataset: {
            source: [
              ["stage", "value"],
              ["Visit", 1000],
              ["Sign Up", 600],
              ["Qualified", 320],
              ["Proposal", 180],
              ["Won", 96],
            ],
          },
          series: [
            {
              type: "funnel",
              encode: { itemName: "stage", value: "value" },
            },
          ],
        },
      },
    ],
  },
};

const CHART_TYPE_ORDER = ["line", "bar", "area", "dualAxis", "scatter", "pie", "gauge", "radar", "funnel"];
const CHART_ORDER = CHART_TYPE_ORDER.slice();

Object.keys(CHART_DEFINITIONS).forEach((chartType) => {
  const localized = LOCALIZED_DEFINITION_TEXT.zh && LOCALIZED_DEFINITION_TEXT.zh[chartType];
  if (!localized) {
    return;
  }
  CHART_DEFINITIONS[chartType].zhLabel = localized.label || CHART_DEFINITIONS[chartType].label;
  CHART_DEFINITIONS[chartType].zhBlurb = localized.blurb || CHART_DEFINITIONS[chartType].blurb;
});

  return {
    COMMON_GROUPS,
    LOCALIZED_DEFINITION_TEXT,
    CHART_DEFINITIONS,
    CHART_TYPE_ORDER,
    CHART_ORDER,
  };
});
